name: Pull request builds

on:
  pull_request:
    types: opened
    branches:
      - main

jobs:
  build_pr:
    name: Build
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build app
        run: |
          npm install
          npm run build
